name: Build pr

on:
  schedule:
    - cron: '0 22 * * 6' # runs at 00:00 CET Saturday

  workflow_dispatch:

jobs:
          
  build_pr_scheduling:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Compile HW Partial Reconfig Scheduling
      run: |
        mkdir build_pr_scheduling_hw && cd build_pr_scheduling_hw
        /usr/bin/cmake ../hw/ -DFDEV_NAME=u55c -DEXAMPLE=pr_scheduling -DACLK_F=250
        make shell && make compile

    - name: Compile SW Partial Reconfig Scheduling
      run: |
        mkdir build_pr_scheduling_sw && cd build_pr_scheduling_sw
        /usr/bin/cmake ../sw -DTARGET_DIR=../sw/examples/pr_scheduling/
        make
