name: CMake

on:
  push:
    branches: [ "dev_txn" ]
  pull_request:
    branches: [ "dev_txn" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    
    - name: Vivado environment activation
      run: source ~runshi/tools/scripts/en_vivado.sh 2022.1 && which vivado

    - name: Compile DLM example
      run: |
        mkdir build_dlm && cd build_dlm
        cmake ../hw/ -DFDEV_NAME=u55c -DVITIS_HLS=1 -DEN_BPSS=1 -DHBM_BPSS=1 -DEN_RDMA_0=1 -DEN_UCLK=1 -DUCLK_F=250 -DAXI_ID_BITS=6 \
        -DEN_IPCACHE=1 -DIPCACHE_DIR=/home/runshi/Workspace/hw/coyote_build/ipcache/20221 \
        -DAPPS=dlm -DAPPS_CONFIG=1t2n1c8p \
        -DN_MEM_CHAN=4 -DEN_MEM_BPSS=1 -DEN_RPC=1
        make shell && make compile
      
    - name: Echo
      run: echo "Hello world!"
